### ISSUE TITLE
[BUG] Computational tasks fail with "werkzeug: bad request" error

### ISSUE THREAD

**Issue by lcdorman** [czbiohub-sf/excellxgene#16]
**Describe the bug**
When I use excellxgene on a server, the computational tasks will not run (reembedding, differential expression). On the terminal log I see a lot of errors such as ERROR:werkzeug:192.168.105.26 - - [29/Aug/2022 21:19:11] code 400, message Bad request version ('server\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00'). The computation never completes. 

**To Reproduce**
I ran excellxgene launch /path/to/file/ --host=0.0.0.0
Packages installed: 
 *Name                   Version                   Build  Channel*
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aniso8601                 9.0.1                    pypi_0    pypi
anndata                   0.7.8                    pypi_0    pypi
annoy                     1.17.1                   pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asttokens                 2.0.8                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
authlib                   1.0.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bbknn                     1.5.1                    pypi_0    pypi
bleach                    5.0.1                    pypi_0    pypi
boto3                     1.24.55                  pypi_0    pypi
botocore                  1.27.55                  pypi_0    pypi
brotli                    1.0.9                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
certifi                   2022.6.15                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cryptography              37.0.4                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecated                1.2.13                   pypi_0    pypi
dill                      0.3.5.1                  pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
excellxgene               2.9.4                    pypi_0    pypi
executing                 0.10.0                   pypi_0    pypi
fbpca                     1.0                      pypi_0    pypi
filelock                  3.8.0                    pypi_0    pypi
flask                     2.2.2                    pypi_0    pypi
flask-compress            1.12                     pypi_0    pypi
flask-cors                3.0.10                   pypi_0    pypi
flask-restful             0.3.9                    pypi_0    pypi
flask-server-timing       0.1.2                    pypi_0    pypi
flask-sock                0.5.2                    pypi_0    pypi
flask-talisman            1.0.0                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
flatten-dict              0.4.2                    pypi_0    pypi
geosketch                 1.2                      pypi_0    pypi
grpcio                    1.43.0                   pypi_0    pypi
gunicorn                  20.1.0                   pypi_0    pypi
h11                       0.13.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
harmonypy                 0.0.6                    pypi_0    pypi
hnswlib                   0.5.2                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
igraph                    0.9.11                   pypi_0    pypi
intervaltree              3.1.0                    pypi_0    pypi
ipykernel                 6.15.1                   pypi_0    pypi
ipython                   8.4.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.1                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jsonschema                4.12.1                   pypi_0    pypi
jupyter-client            7.3.4                    pypi_0    pypi
jupyter-core              4.11.1                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.1                    pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
leidenalg                 0.8.10                   pypi_0    pypi
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.39.2               h753d276_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
llvmlite                  0.35.0                   pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
nbclient                  0.6.7                    pypi_0    pypi
nbconvert                 7.0.0                    pypi_0    pypi
nbformat                  5.4.0                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.5                    pypi_0    pypi
notebook                  6.4.12                   pypi_0    pypi
numba                     0.52.0                   pypi_0    pypi
numexpr                   2.8.3                    pypi_0    pypi
numpy                     1.21.5                   pypi_0    pypi
openssl                   3.0.5                h166bdaf_1    conda-forge
packaging                 21.3                     pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.4.0                    pypi_0    pypi
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.30                   pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyjwt                     2.4.0                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
python                    3.8.13          ha86cf86_0_cpython    conda-forge
python-dotenv             0.20.0                   pypi_0    pypi
python-igraph             0.9.11                   pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pyzmq                     23.2.1                   pypi_0    pypi
ray                       1.11.0                   pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
redis                     4.3.4                    pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
s3fs                      0.4.2                    pypi_0    pypi
s3transfer                0.6.0                    pypi_0    pypi
sam-algorithm             1.0.0                    pypi_0    pypi
scanorama                 1.7.2                    pypi_0    pypi
scanpy                    1.8.2                    pypi_0    pypi
scikit-learn              1.0.1                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                65.0.2           py38h578d9bd_0    conda-forge
simple-websocket          0.8.0                    pypi_0    pypi
sinfo                     0.3.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
sqlite                    3.39.2               h4ff8645_1    conda-forge
stack-data                0.4.0                    pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
terminado                 0.15.0                   pypi_0    pypi
texttable                 1.6.4                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
tornado                   6.2                      pypi_0    pypi
traitlets                 5.3.0                    pypi_0    pypi
typing-extensions         4.3.0                    pypi_0    pypi
urllib3                   1.26.11                  pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.1                    pypi_0    pypi
wrapt                     1.14.1                   pypi_0    pypi
wsproto                   1.1.0                    pypi_0    pypi
xlrd                      1.2.0                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.8.1                    pypi_0    pypi

**Expected behavior**
Differential expression calculation in < 10 minutes for ~300 vs 800 cells. 

**Screenshots**
![Screen Shot 2022-08-29 at 2 32 26 PM](https://user-images.githubusercontent.com/33703031/187303016-17f9df37-d585-4578-8c6d-f8befa79b4e1.png)

**Version (please complete the following information):**
 - hosted on a server (--host tag)
 - Chrome
 - Version: **2.9.4**

**Additional context**
Others can run this program on the same server. Their installations were earlier so I believe it may be an issue either with the most recent version or a dependency break in some newly updated package.

**Comment by lcdorman** [comment]
This is a problem with 2.9.4; version 2.9.2 works fine.

**Comment by yangjun9095** [comment]
Closing this issue as we have version 2.9.2 as the main version now.
