### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lcdorman** [czbiohub-sf/excellxgene#18]
Excellxgene (2.9.2) doesn't work with Anndata 0.8.0, only with 0.7. Are there plans to upgrade to Anndata 0.8.0? I'm getting incompatibility issues with scvi, scanpy, and anndata when I try to only use anndata 0.7.8 for all analyses.

**Comment by jhkliu42** [comment]
I managed to fix this by installing excellxgene as normal and then manually updating anndata (`pip install anndata==0.8.0`). This resolved issues with loading .h5ad files that had anndata versioning errors.
